apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  ingress_type: Ingress
  ingress_class_name: nginx
  hostname: awx.local
  admin_password_secret: admin-password
  create_preload_data: false
  replicas: 1
  image_pull_policy: Always
  image_version: 24.6.1
  image: quay.io/ansible/awx:24.6.1
  extra_settings:
  - setting: TOWER_URL_BASE
    value: '"http://awx.local"'
  ipv6_disabled: true
  postgres_data_volume_init: true
  postgres_init_container_commands: |
    chown 26:0 /var/lib/pgsql/data
    chmod 700 /var/lib/pgsql/data
