run:
  deadline: 3m

issues:
  exclude-rules:
    - path: tools/tfplugindocs/tools.go
      linters:
        - typecheck
    - path: internal/provider/provider_test.go
      linters:
        - deadcode
        - unused
        - varcheck
