apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/1/env/-
      value: { "name": "DEFAULT_AWX_VERSION", "value": "24.3.1" }
  target:
    version: v1
    group: apps
    kind: Deployment
    name: awx-operator-controller-manager

resources:
- ../../base
