// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/client/client.go -destination=internal/resource/client_mock_test.go -package=resource_test -typed
//

// Package resource_test is a generated GoMock package.
package resource_test

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	models "github.com/ilijamt/terraform-provider-awx/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockClient) Do(ctx context.Context, req *http.Request) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, req)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockClientMockRecorder) Do(ctx, req any) *MockClientDoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockClient)(nil).Do), ctx, req)
	return &MockClientDoCall{Call: call}
}

// MockClientDoCall wrap *gomock.Call
type MockClientDoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDoCall) Return(data map[string]any, err error) *MockClientDoCall {
	c.Call = c.Call.Return(data, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDoCall) Do(f func(context.Context, *http.Request) (map[string]any, error)) *MockClientDoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDoCall) DoAndReturn(f func(context.Context, *http.Request) (map[string]any, error)) *MockClientDoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewRequest mocks base method.
func (m *MockClient) NewRequest(ctx context.Context, method, endpoint string, body io.Reader) (*http.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRequest", ctx, method, endpoint, body)
	ret0, _ := ret[0].(*http.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewRequest indicates an expected call of NewRequest.
func (mr *MockClientMockRecorder) NewRequest(ctx, method, endpoint, body any) *MockClientNewRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRequest", reflect.TypeOf((*MockClient)(nil).NewRequest), ctx, method, endpoint, body)
	return &MockClientNewRequestCall{Call: call}
}

// MockClientNewRequestCall wrap *gomock.Call
type MockClientNewRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientNewRequestCall) Return(arg0 *http.Request, arg1 error) *MockClientNewRequestCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientNewRequestCall) Do(f func(context.Context, string, string, io.Reader) (*http.Request, error)) *MockClientNewRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientNewRequestCall) DoAndReturn(f func(context.Context, string, string, io.Reader) (*http.Request, error)) *MockClientNewRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// User mocks base method.
func (m *MockClient) User(ctx context.Context) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockClientMockRecorder) User(ctx any) *MockClientUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockClient)(nil).User), ctx)
	return &MockClientUserCall{Call: call}
}

// MockClientUserCall wrap *gomock.Call
type MockClientUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUserCall) Return(arg0 models.User, err error) *MockClientUserCall {
	c.Call = c.Call.Return(arg0, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUserCall) Do(f func(context.Context) (models.User, error)) *MockClientUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUserCall) DoAndReturn(f func(context.Context) (models.User, error)) *MockClientUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
